#!/bin/bash

cpufreq-set -c 0 -f 3.3GHz
cpufreq-set -c 1 -f 3.3GHz
cpufreq-set -c 2 -f 3.3GHz
cpufreq-set -c 3 -f 3.3GHz
cpufreq-set -c 4 -f 3.3GHz
cpufreq-set -c 5 -f 3.3GHz
cpufreq-set -c 6 -f 3.3GHz
cpufreq-set -c 7 -f 3.3GHz
